# theme: jekyll-theme-architect
# theme: jekyll-theme-minimal
remote_theme: rundocs/jekyll-rtd-theme
title: Architect cheatsheet
description: Architect is a theme for GitHub Pages.
show_downloads: false
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions