# theme: jekyll-theme-architect
# theme: jekyll-theme-minimal
remote_theme: rundocs/jekyll-rtd-theme
title: Architect cheatsheet
description: description
show_downloads: false
plugins:
  - jekyll-relative-links
