# theme: jekyll-theme-architect
# theme: jekyll-theme-minimal
remote_theme: rundocs/jekyll-rtd-theme
title: Architect cheatsheet
description: Architect cheatsheet by Isidoro Mercogliano.
show_downloads: true

fluid: true

plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

readme_index:
  with_frontmatter: true

author: [Isidoro Mercogliano]
lang: en

copyright: false
edit: false
logo: false # relative path to your image, eg: assets/logo.png
disqus: false # your disqus username

nav_version: false
addons: false
addons_branch: false





# set true will show the addons with blank content
addons: true


# custom github list items, the order is avaiable
addons:
  - github:
    - homepage
    - issues
    - download

addons_branch: true # show github pages source branch