# theme: jekyll-theme-architect
# theme: jekyll-theme-minimal
remote_theme: rundocs/jekyll-rtd-theme
title: Architect cheatsheet
description: Architect is a theme for GitHub Pages.
show_downloads: false

fluid: true

plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions



readme_index:
  with_frontmatter: true

author: [site.github.owner_name]
lang: en

copyright: false
edit: false
logo: false # relative path to your image, eg: assets/logo.png
disqus: false # your disqus username

nav_version: false
addons: false
addons_branch: false

rougify: github # more styles see code highlight